version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    environment:
      - VITE_NODE_API_URL=http://node:3000

  node:
    volumes:
      - ./nodejs-backend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

  fastapi:
    volumes:
      - ./fastapi-backend:/app
    command: ["uv", "run", "app/main.py", "--host", "0.0.0.0", "--port", "8000"]
