[project]
name = "fastapi-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "geoalchemy2>=0.18.0",
    "shapely>=2.1.1",
    "uvicorn>=0.35.0",
]
